version: "3"

services:
  api:
    image: mtt/ifg:dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./public:/home/node/app/public
    ports:
      - "8001:3000"
    command: ["yarn", "start:watch"]
    depends_on:
      - db
  db:
    image: mongo:4
    ports:
      - "27037:27017"
