version: "3.3"

services:
  api:
    image: mtt/ifg:dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./public:/home/node/app/public
    ports:
      - "8001:3000"
    command: ["yarn", "start:watch"]
    depends_on:
      - mongodb-server
    secrets:
      - admin
      - firebaseDatabaseURL
      - serviceAccountKey
    environment:
      ADMIN: "/run/secrets/admin"
      FIREBASE_DATABASE_URL: "/run/secrets/firebaseDatabaseURL"
      FIREBASE_SERVICE_ACCOUNT: "/run/secrets/serviceAccountKey"
  mongodb-server:
    image: mongo:4
    ports:
      - "27037:27017"
secrets:
  admin:
    file: ./secrets/admin.json
  firebaseDatabaseURL:
    file: ./secrets/firebaseDatabaseURL
  serviceAccountKey:
    file: ./secrets/serviceAccountKey.json
