version: '3'

services:
  api:
    image: mtt/ifg:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - ./src:/usr/ifg/src
    ports:
    - '8001:3000'
    depends_on:
    - db
  db:
    image: mongo:4
    ports:
    - '27037:27017'

