version: "2"
services:
  api:
    image: registry.mttjsc.com/i-feel-good/ifg_server:master
    expose:
      - "3000"
    depends_on:
      - db
    secrets:
      - ifg_admin_info
      - ifg_service_account_key
      - ifg_firebase_database_url
    environment:
      NODE_ENV: production
      VIRTUAL_PORT: "3000"
      VIRTUAL_HOST: api.ifeelgood.mttjsc.com
      LETSENCRYPT_HOST: api.ifeelgood.mttjsc.com
      LETSENCRYPT_EMAIL: linh.le@mttjsc.com
      ADMIN: "/run/secrets/ifg_admin_info"
      FIREBASE_SERVICE_ACCOUNT: "/run/secrets/ifg_service_account_key"
      FIREBASE_DATABASE_URL: "/run/secrets/ifg_firebase_database_url"
    labels:
      io.rancher.container.system: MTT-LOCAL
      io.rancher.container.pull_image: always

  db:
    image: mongo:4
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - /mtt-ready/i-feel-good/mongodb:/data/db
    ports:
      - "27037:27017"
    command:
      - mongod
      - --smallfiles
      - --logpath=/dev/null
    labels:
      io.rancher.container.system: MTT-LOCAL
      io.rancher.container.pull_image: always

secrets:
  ifg_admin_info:
    external: "true"
  ifg_service_account_key:
    external: "true"
  ifg_firebase_database_url:
    external: "true"
